### PR TITLE
Update almanac to latest struct

### PR DESCRIPTION
**Pull request by ljbade**
Updates almanac class to match fields used in https://github.com/swift-nav/libswiftnav/pull/269

### CODE REVIEW

**Comment by ljbade** [comment]
Ready for review @swift-nav/estimation

**Comment by ljbade** [comment]
@dzollo Why would I get:
```
$ kill -n 9  $PID
/home/travis/build.sh: line 45: kill: (10853) - No such process
The command "kill -n 9  $PID" exited with 1.
```

in Travis?

**Comment by denniszollo** [comment]
I have things setup to run the console, sleep for 10 seconds, and then try and kill the console.  If the console isn't running 10 seconds later, it throws that error in travis.  

Look up above in the log and you will see the reason why.

**Comment by denniszollo** [comment]
This error however, is something weird about travis: 
/usr/bin/git
WARNING:traits.has_traits:DEPRECATED: traits.has_traits.wrapped_class, 'the 'implements' class advisor has been deprecated. Use the 'provides' class decorator.
Traceback (most recent call last):
  File "piksi_tools/console/console.py", line 125, in <module>
    from piksi_tools.console.tracking_view import TrackingView
  File "/home/travis/build/swift-nav/piksi_tools/piksi_tools/console/tracking_view.py", line 12, in <module>
    from chaco.api import BarPlot, ArrayDataSource, DataRange1D, LinearMapper, \
  File "/usr/local/lib/python2.7/dist-packages/chaco/api.py", line 37, in <module>
    from abstract_plot_renderer import AbstractPlotRenderer
  File "/usr/local/lib/python2.7/dist-packages/chaco/abstract_plot_renderer.py", line 7, in <module>
    from plot_component import PlotComponent
  File "/usr/local/lib/python2.7/dist-packages/chaco/plot_component.py", line 4, in <module>
    from enable.api import Component
  File "/usr/local/lib/python2.7/dist-packages/enable/api.py", line 21, in <module>
    from markers import MarkerTrait, marker_trait, MarkerNameDict, marker_names, \
  File "/usr/local/lib/python2.7/dist-packages/enable/markers.py", line 18, in <module>
    from compiled_path import CompiledPath
  File "/usr/local/lib/python2.7/dist-packages/enable/compiled_path.py", line 17, in <module>
    from toolkit import toolkit_object
  File "/usr/local/lib/python2.7/dist-packages/enable/toolkit.py", line 47, in <module>
    _init_toolkit()
  File "/usr/local/lib/python2.7/dist-packages/enable/toolkit.py", line 35, in _init_toolkit
    __import__(backend)
  File "/usr/local/lib/python2.7/dist-packages/enable/qt4/image.py", line 13, in <module>
    from kiva.agg import CompiledPath, GraphicsContextSystem as GraphicsContext
  File "/usr/local/lib/python2.7/dist-packages/kiva/agg/__init__.py", line 19, in <module>
    from plat_support import PixelMap
  File "/usr/local/lib/python2.7/dist-packages/kiva/agg/plat_support.py", line 161, in <module>
    resize_gl = _plat_support.resize_gl
AttributeError: 'module' object has no attribute 'resize_gl'

Some of the Travis servers exhibit this behavior, and some do not. You can safely ignore this as it is not a regression but a consistent bug.

**Comment by denniszollo** [comment]
However please add some sanity checking unit test coverage if you are able!

**Pull request closed without merging**
