### PR TITLE
Handle L1P and L2P. Fix bugs in calculating GPS PRN numbers.

### PR DESCRIPTION
**Pull request by ljbade**
Not sure what do with `acq_results.py`. Looks like it needs TLCm but we will be changing that message anyway in https://github.com/swift-nav/libsbp/pull/384

### CODE REVIEW

**Comment by ljbade** [comment]
Hmm how do I get the SID `constellation`, seems its undefined?

**Comment by ljbade** [comment]
Tested using Skylark stream:
image

Works.

**Comment by ljbade** [comment]
@denniszollo can you review/merge

**Comment by denniszollo** [comment]
LGTM - merging.

I think we should put these tables of code to signal identifier right into the SBP library when we make the new messages.

**Comment by ljbade** [comment]
@denniszollo yes I agree, we should have enum constants or something

**Pull request merged**
