### PR TITLE
Console list tweaks

### PR DESCRIPTION
**Pull request by denniszollo**
This PR does the following per feedback from sprint exit on 08/21:

* adds a mouseover on log level filter to help tell people how the filtering works
* adds  a command line argument to console set initial log level filter of console
* removes lines on the tabular view of the console output
* puts newlines which exist for formatting of the log/print message as separate rows in the table

### CODE REVIEW

**Comment by denniszollo** [comment]
@cbeighley 
Would you mind reviewing?  This address feedback from team after last sprint about the console list view.

**Comment by cbeighley** [comment]
Tested and looks good to merge. One slight note is that I am seeing a Log Level : Console that is not in the drop down list of log levels, which is slightly confusing.

**Comment by denniszollo** [comment]
the "console" log level I set up so that you could not filter it out because I didn't know where on the severity spectrum it should live.  Maybe it would be better if we did the checkboxes as you suggested

**Comment by cbeighley** [comment]
That works for me. Maybe that could be noted in the hover tip text?

**Comment by denniszollo** [comment]
Noted in hover tip text. Merging this.

**Pull request merged**
