### PR TITLE
Setting to file gui

### PR DESCRIPTION
**Pull request by denniszollo**
Add ability for console to read and write settings from an ini file.

### CODE REVIEW

**Comment by denniszollo** [comment]
How to we feel about moving the "toolbar" buttons as shown below?
New:
image
Old:
image

**Comment by denniszollo** [comment]
New Option B is:
image

**Comment by denniszollo** [comment]
New options C:
image

**Comment by pmiettinen** [comment]
`Write from File` seems a bit off. Usually file is being read from?

**Comment by pmiettinen** [comment]
And maybe consider using either `Save` and `Load` or `Write` and `Read`?

**Comment by denniszollo** [comment]
Thanks Pas for feedbacki.  Based upon your comments, I will rename the "write from file" to "load from file".

**Comment by denniszollo** [comment]
My Final answer is here:
image

**Comment by denniszollo** [comment]
This has been tested extensively by Sergio and Myself and I think it is ready to go.

**Pull request merged**
