### PR TITLE
Make sure new console works with v0.21 firmware WRT skylark and sbp_r…

### PR DESCRIPTION
**Pull request by denniszollo**
…elay.

### CODE REVIEW

**Comment by mfine** [comment]
We should kill these whitelists.

**Comment by denniszollo** [comment]
How do you mean?

**Comment by denniszollo** [comment]
we have very limited bandwidth in the pixhawk use case so only really want to send one type of message.

**Comment by mfine** [comment]
Ok, then remove the white lists from serial link - that has nothing to do with pixhawk, and these white lists are brittle and general not a good idea.

**Comment by denniszollo** [comment]
So you think we have the skylark client send the whole stream instead then?

**Comment by mfine** [comment]
Yup. That's what the other clients are doing.

**Pull request merged**
