### PR TITLE
Change scaling on Magnetomter view

### PR DESCRIPTION
**Pull request by denniszollo**
Should allow it to show some detail in Earth's field while still not saturating if a magnet is nearby.

/cc @axlan

### CODE REVIEW

**Comment by axlan** [comment]
This doesn't saturate from a fridge magnet being within 6 inches?

**Comment by denniszollo** [comment]
I bet it saturates, but as it was rotating the board showed no change on the graph.   Perhaps we just need to dynamically scale instead

**Comment by denniszollo** [comment]
I changed this so that it dynamically scales based upon what has bee received.

**Comment by axlan** [comment]
LGTM

**Pull request merged**
