### PR TITLE
Hide rinex record, fixed width table font and formatting, add lock

### PR DESCRIPTION
**Pull request by denniszollo**
#327

### CODE REVIEW

**Comment by ljbade** [comment]
A few things: add flags column for 1/2 cycle amb.

For the the validity flags the column value should be blank if the value is not valid.

Finally 0 cno means value is invalid so should set blank if zero.

**Comment by ljbade** [comment]
Also should lock time be shown in seconds or Ms?

**Comment by ljbade** [comment]
I can test this for you tomorrow using my new observations firmware PR

**Comment by denniszollo** [comment]
I'm testing on the old obs message; I agree with everything and will update tonight.  I think I will put locktime in raw and converted to seconds.

**Comment by ljbade** [comment]
@denniszollo ah ok

**Pull request closed without merging**
