### PR TITLE
Handler starts the link

### PR DESCRIPTION
**Pull request by mfine**
Handler takes care of starting the link. See https://github.com/swift-nav/libsbp/pull/170. Needs to go in first and pick up a new sbp dependency.

/cc @cbeighley

### CODE REVIEW

**Comment by cbeighley** [comment]
lgtm

**Comment by denniszollo** [comment]
sbp log analysis device runner will need to be udpdated as well

**Comment by denniszollo** [comment]
Is there a possibility that early messages are ignored because the link starts before callbacks are registered?

**Comment by cbeighley** [comment]
I think you'll drop those messages anyway.

**Comment by mfine** [comment]
Is there anywhere that we're depending on receiving messages before callbacks are registered? That sounds like a race condition we should avoid.

**Comment by mfine** [comment]
@denniszollo sbp_log_analysis isn't using the context manager, shouldn't need any updates to take this change.

**Comment by mfine** [comment]
When the `libsbp` change gets ok'd, I'll bring this in with a new `libsbp` version.

**Comment by mfine** [comment]
Bringing this in.

**Pull request merged**
