### PR TITLE
Versions Discovery

### PR DESCRIPTION
**Pull request by mfine**
Determine the versions of the bootloader and sbp and write them to a file. Contents of file look like:

```json
{
  "bootloader": "v1.2",
  "sbp": 0
}
```

Are there more versions to capture from the device?

/cc @mookerji @cbeighley

### CODE REVIEW

**Comment by mookerji** [comment]
From device1_settings.txt:

```
nap_version          v0.12-39-gbd5edfc
serial_number        1226
firmware_version     v0.16-baseline_update-10-g44115b9
hw_revision          piksi_2.3.1
```
 ... in addition to what you mentioned.

**Comment by cbeighley** [comment]
There are also the NAP key, STM Unique ID, and NAP device dna, but they're not versions persay.

**Comment by mfine** [comment]
Those should be covered in settings - see the sample output in #71 under `system_info`.

But hmm, maybe we should just collect all the things into one output? Including the other stuff like NAP key, STM UniqueID, and NAP device DNA?

Instead of settings - it'd be more like diagnostics or something?

**Comment by mookerji** [comment]
:+1: single data file

**Comment by mfine** [comment]
Closing this in favor of merging it into #71.

**Pull request closed without merging**
