### PR TITLE
Bootloader tests

### PR DESCRIPTION
**Pull request by mfine**
Revive the bootloader tests branch.

/cc @gsmcmullin @cbeighley

### CODE REVIEW

**Comment by mfine** [comment]
I revived the bootloaders tests branch and rebased it on master. This is definitely worth some review. Its potentially broken in some areas where the iterator approach has changed things. @gsmcmullin

**Comment by mfine** [comment]
Checked out a handful of scripts and things seemed ok. But python.

**Comment by cbeighley** [comment]
Sorry for the flow reply. Looks good. `run_bootloader_tests.sh` is missing some stuff, not sure how that happened - I'll find it and make a PR after this is merged.

**Comment by mfine** [comment]
The abandoned branch should have been: https://github.com/swift-nav/piksi_tools/blob/colin-master/piksi_tools/testing/run_bootloader_tests.sh

**Comment by mfine** [comment]
Going to bring this in.

**Pull request merged**
