### PR TITLE
Fixes installation of libffi-dev and libssl-dev.

### PR DESCRIPTION
**Pull request by rge-exafore**
This fix was verified on clean Ubuntu 14.04 installation.
@JoshuaGross please check.

### CODE REVIEW

**Comment by JoshuaGross** [comment]
Looks reasonable but both the tests are failing - can you look into that?

**Comment by JoshuaGross** [comment]
It's actually possible that the build has been failing for a while regardless of this pull request - @mookerji?

**Comment by rge-exafore** [comment]
I think it fails because of some other error:

Downloading/unpacking PIL (from enable==4.4.1)
  Could not find any downloads that satisfy the requirement PIL (from enable==4.4.1)
Cleaning up...
No distributions at all found for PIL (from enable==4.4.1)
Storing debug log for failure in /Users/travis/Library/Logs/pip.log
make: *** [deps] Error 1

**Comment by mookerji** [comment]
Hey, @rge-exafore : Can you try removing the `--allow-external PIL` line here: https://github.com/swift-nav/piksi_tools/commit/6f0241dcf428c9fcacac628cac02adf0f40ca9b8 and see if the OS X builder on travis works? The bug in question is here: https://travis-ci.org/swift-nav/piksi_tools/jobs/101901703#L3252

**Comment by JoshuaGross** [comment]
One other nit-picky thing: please add comments around this to specify why `git` and the other dependencies are needed, and on what platform. It's not clear by looking at this commit history, or the code, why this was changed. In 3 months or 6 months someone might inadvertently change or delete this.

Other than that, let's try to get the build passing. Besides that it looks great.

**Pull request closed without merging**
