### PR TITLE
Update tracking_view.py

### PR DESCRIPTION
**Pull request by mbavaro**
should we remove that +1?

### CODE REVIEW

**Comment by pmiettinen** [comment]
We should retain the +1 in case of the deprecated tracking message.

**Comment by mbavaro** [comment]
sure... but isn't that +1 here?
https://github.com/swift-nav/piksi_tools/blob/master/piksi_tools/console/tracking_view.py#L177

**Comment by ljbade** [comment]
Yes I think it is best to do the +1 in the functions specific to the old messages

**Comment by mbavaro** [comment]
So Leith if you agree I'd merge..

**Comment by ljbade** [comment]
Yes, if you have tested it with both current and the old message

**Comment by mbavaro** [comment]
closing as Keerthan is embracing it!

**Pull request closed without merging**
