### PR TITLE
Sbp log zipper

### PR DESCRIPTION
**Pull request by njoubert**
Adds a utility that takes two SBP JSON log files, one from a base station and one from a rover, and interleaves them into a single SBP file. The resulting SBP file can be post-processed using our filter to create a baseline.

### CODE REVIEW

**Comment by RaiBearG** [comment]
very nice. is the idea to not go the real time route ? log the base, log the rover (on the uav) and get position (rtk) data for triggers or whatever else, in post production ?

**Comment by njoubert** [comment]
@RaiBearG Yes, I'm demoing a post-processing kinematics solution on top of the SBP2 driver. It's a tech demo that will help us move forward on what an end-to-end PPK solution might look like.

**Comment by denniszollo** [comment]
Niels.  Code looks good.  
Can we put some comments and exposition about what it's for?  Suggestion is a doc string on main?
Can we file the template from the other script for the header and copyright stuff?

**Comment by njoubert** [comment]
@denniszollo added!

**Pull request merged**
