### PR TITLE
CONSOLE: hide expert settings by default

### PR DESCRIPTION
**Pull request by henryhallam**
cc @denniszollo @gsmcmullin @fnoble  
Any setting category beginning with "expert" will be hidden unless -e is passed on the console command line.

### CODE REVIEW

**Comment by denniszollo** [comment]
What do we think about adding an expert flag to the Yaml file instead?

**Comment by denniszollo** [comment]
There are many settings that aren't in an "expert" group that are really expert settings, such as the kalman filter tuning parameters

**Comment by denniszollo** [comment]
Also, what if the some settings in a group are expert and some are not?  I don't want to rename settings unless we have to.

**Comment by cbeighley** [comment]
+1 I think a flag is the way to go

**Comment by fnoble** [comment]
+1 on flag

**Comment by henryhallam** [comment]
Even though it's not yet July 4th:
*waves flag*

How's this look?

**Comment by denniszollo** [comment]
LGTM

**Pull request merged**
