### PR TITLE
Documentation for decimating raw IMU messages by factor of 50 [ESD-1014]

### PR DESCRIPTION
**Pull request by cbeighley**
Companion PR to https://github.com/swift-nav/piksi_buildroot/pull/1113

If you don't merge this, note that the default whitelist settings documentation in settings.yaml needs to get updated (done in this PR).

### CODE REVIEW

**Comment by denniszollo** [comment]
@cbeighley Did we change this for 2.3 such that we need to update this setting?

**Comment by silverjam** [comment]
@denniszollo we didn't enable the IMU by default in 2.3 afaik, @benjaminaltieri ?

**Comment by benjaminaltieri** [comment]
@denniszollo @silverjam we implemented a variant that only activates IMU by default if INS is active (PR describing that here: https://github.com/swift-nav/piksi_buildroot/pull/1202)

**Comment by silverjam** [comment]
Close?

**Pull request closed without merging**
