### PR TITLE
New sbp with new bootloader messages

### PR DESCRIPTION
**Pull request by mfine**
Pick up the new sbp and start using the new bootloader messages.

/cc @cbeighley

### CODE REVIEW

**Comment by mfine** [comment]
Can add a `-x` experimental flag to enable sending the new style messages out - or is there a better approach here?

**Comment by mfine** [comment]
Setup branches to choose between message types - just need logic to drive that choice.

**Comment by mfine** [comment]
Added logic checks for `< 2.0`

**Comment by cbeighley** [comment]
lgtm

**Comment by mfine** [comment]
Going to bring this in.

**Pull request merged**
