### PR TITLE
Add 'system_monitor.watchdog' setting to enable/disable watchdog timer.

### PR DESCRIPTION
**Pull request by henryhallam**

### CODE REVIEW

**Comment by mfine** [comment]
Settings look good to me - @denniszollo?

**Comment by fnoble** [comment]
I wouldn't worry about putting the firmware version in there, if the setting doesn't exist in the firmware then it won't show up

The list of settings is stored on the device - the YAML is just to cross reference the descriptions.

**Comment by henryhallam** [comment]
@fnoble Oh, good point.
Incidentally, for the ext_events should I bump the required NAP revision?  It's currently ancient, 0.9something. Or is it better to not require users to upgrade their NAP, and just leave the feature nonfunctional?

**Comment by fnoble** [comment]
I would bump the NAP version if the FW won't work without it. I'd leave it if it just won't detect events.

**Pull request merged**
